server {
    listen 80;
    server_name rooster.com;

    resolver 8.8.8.8;

    location / {
        set $target test.rooster.com;
        proxy_pass http://$target;
        proxy_set_header Host $host;
    }
}
